export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';
export const FECTH_ARTICLE = 'FECTH_ARTICLE';
export const ADD_PAGINATION_DATA = 'ADD_PAGINATION_DATA';
export const ADD_LATEST_ARTICLE = 'ADD_LATEST_ARTICLE';
export const SHOW_LOAD_MORE_BTN = 'SHOW_LOAD_MORE_BTN';
export const ADD_TOTAL_ARTICLE_FETCHED = "ADD_TOTAL_ARTICLE_FETCHED"
export const UPDATE_PAGINATION_COUNT = "UPDATE_PAGINATION_COUNT"
